### ISSUE TITLE
Starter code for Backend

### ISSUE THREAD

**Issue by E-Cell-IIIT-Surat** [E-Cell-IIIT-Surat/Newsletter#1]
# What to do?
Write the starter code for Backend.
- [ ] Starter Index.js file
- [ ] Folder structure with Models and middleware

### Follow the Contribution guidelines

**Comment by prakhar728** [comment]
I'd like to work on this issue. Please assign it to me.

**Comment by its-me-Harsh-Anand** [comment]
Hey @prakhar728, Can you please assign this issue to me?
I would like to work on it

**Comment by E-Cell-IIIT-Surat** [comment]
> Hey @prakhar728, Can you please assign this issue to me? I would like to work on it

@its-me-Harsh-Anand We'll be opening all new issues today. Please try your hands on them.

**Comment by its-me-Harsh-Anand** [comment]
> > Hey @prakhar728, Can you please assign this issue to me? I would like to work on it
> 
> @its-me-Harsh-Anand We'll be opening all new issues today. Please try your hands on them.

Sure
