### ISSUE TITLE
Create Starter code for Frontend

### ISSUE THREAD

**Issue by E-Cell-IIIT-Surat** [E-Cell-IIIT-Surat/Newsletter#3]
Add a React starter template for frontend. Vite is preferred.

**Comment by rupak2001** [comment]
Hi, can i contribute in this issue?
Let me know if you want it in the frontend branch or main?

**Comment by its-me-Harsh-Anand** [comment]
> Add a React starter template for frontend. Vite is preferred.

Hey can you please assign it to me?

**Comment by E-Cell-IIIT-Surat** [comment]
> Hi, can i contribute in this issue? Let me know if you want it in the frontend branch or main?

Assigned.
