### ISSUE TITLE
Add a backend to signup for the news letter

### ISSUE THREAD

**Issue by Har-sh-arma** [E-Cell-IIIT-Surat/Newsletter#5]
make a directory containing the actions that would be taken by the server. 
1.Adding user to the Newsletter Subscriber list
2.Detecting admin login

**Comment by E-Cell-IIIT-Surat** [comment]
@Har-sh-arma You can start working on the issue.

**Comment by Har-sh-arma** [comment]
![image](https://user-images.githubusercontent.com/90756795/198024765-988c7658-42ce-4a06-834a-53687c1000b7.png)
