### ISSUE TITLE
Newsletter page Design

### ISSUE THREAD

**Issue by E-Cell-IIIT-Surat** [E-Cell-IIIT-Surat/Newsletter#8]
Create a page for the newsletter page.
Requirements:-
- [ ] Should have an input box for emails
- [ ]  Should have a good background
- [ ] Use the Ruminate color pallete

Create the design, add it to a readme file titled **Designs.md**, and add the figma link

**Comment by vanshikagoel1** [comment]
I can work on this issue, please assign it to me.

**Comment by E-Cell-IIIT-Surat** [comment]
> I can work on this issue, please assign it to me.

Go ahead
